/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Commands
         * @description Enqueue an intent. 201 if new, 200 if a dedupe returned the existing row.
         */
        post: operations["post_commands_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commands/{command_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Command
         * @description Read one command's status through the read-only engine.
         */
        get: operations["get_command_commands__command_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commands/{command_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Command
         * @description Supply the confirm token for a live-mode order-reaching intent.
         *
         *     In paper mode no token was issued, so this is a no-op 204. In live mode a mismatched
         *     or missing token returns 409. A command not awaiting confirmation (already applied,
         *     or not an order-reaching kind) also returns 409.
         */
        post: operations["confirm_command_commands__command_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nav */
        get: operations["nav_nav_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvals
         * @description List approvals, pending by default. ``status=all`` returns decided ones too.
         *
         *     An unknown status value is rejected with 422 (not a silent empty list) — an
         *     operator typo should surface, not look like "no approvals."
         */
        get: operations["list_approvals_options_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Approval
         * @description One approval in full. 404 if unknown. Joined enrichment degrades to null.
         */
        get: operations["get_approval_options_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/assessed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assessed
         * @description The assessed browser: every contract the scan priced, grouped by symbol.
         */
        get: operations["list_assessed_options_assessed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Controls
         * @description Autonomy rung, halt state, mode, and command-drain health.
         */
        get: operations["controls_options_controls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fills
         * @description Recent fills within the last ``days`` days.
         */
        get: operations["list_fills_options_fills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orders
         * @description Working orders by default. ``state=all`` returns everything.
         *
         *     An unknown state value is rejected with 422 (not a silent empty list).
         */
        get: operations["list_orders_options_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/options/shorts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Shorts
         * @description Open short option positions from the most recent position snapshot.
         *
         *     ``as_of`` is the snapshot's capture time, not request time — the same discipline
         *     P0/P1 M4 fixed for quotes. Long options and stock are excluded. ``delta`` carries
         *     its source through ``Sourced`` so a BS delta never looks identical to an IBKR one.
         *     A position with no snapshot data returns ``null`` for ``mark`` and
         *     ``unrealized_pnl``, never ``0.0``.
         */
        get: operations["list_shorts_options_shorts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendations
         * @description The scan's buy-to-own list, rendered exactly as it was scored.
         *
         *     Reads ``BuyCandidateRow`` through the **read-only** trading session (§4.3 — the API
         *     writes nothing). The web layer does no re-scoring: every field is what the
         *     orchestrator's scan-time scoring produced, so the site and the Telegram card
         *     can never disagree about what the system thinks. An empty table returns an empty
         *     list with a 200, not a 404 — no scan has run yet is a legitimate state.
         */
        get: operations["recommendations_research_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Rank: exact ticker, then ticker prefix, then name substring.
         *
         *     Each band is alphabetical within itself. A blank query returns no results rather
         *     than the whole table.
         */
        get: operations["search_research_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sectors
         * @description Sector cards: aggregate daily change, best/worst mover, count, and average IV rank.
         *
         *     Membership comes from ``universe.yaml``'s ``sectors`` map (every universe symbol tagged
         *     with its sector). ``change_pct`` is the warm-tier quote's daily change from the research
         *     DB; a sector with no priced members reports ``change_pct`` as ``None``, never ``0``.
         *     ``avg_iv_rank`` averages only members that actually have IV history in the trading DB
         *     (read-only), and the card carries the contributing count so a one-name average is visible.
         *
         *     Cards are returned ordered by ``avg_iv_rank`` descending (premium richness is the
         *     reason to look); sectors with no IV history sort last, preserving their file order.
         */
        get: operations["sectors_research_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis
         * @description Full analysis for one symbol.
         *
         *     404 only when the symbol is not a known filer. Everything else degrades per section.
         */
        get: operations["analysis_research__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bars
         * @description Daily OHLCV with server-side SMA 50 and 200, in lightweight-charts' field names.
         *
         *     ``time`` is ``YYYY-MM-DD`` (lightweight-charts' accepted daily format). SMA 50 and 200
         *     are computed from ``daily_bars`` here so the chart and the technical panel can never
         *     disagree. A symbol with no bars returns empty lists, not an error.
         */
        get: operations["bars_research__symbol__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{symbol}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Options Lens
         * @description On-demand options-income lens — honest about what it does and doesn't know.
         *
         *     A universe symbol gets real `iv_rank`/`vrp_points` from the trading DB, read-only
         *     (§4.3). An off-universe symbol gets the same shape with `UNKNOWN` and
         *     `coverage.iv_history` false rather than a percentile invented from a short series.
         *     `coverage.option_chain` is always false in P1 — the API holds no IBKR connection, so
         *     `atm_open_interest`/`atm_spread_pct` stay `UNKNOWN` too. Leverage warnings (Task 5.4)
         *     are included for leveraged names via the shared `warnings_for` catalogue.
         */
        get: operations["options_lens_research__symbol__options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{symbol}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Return a cached summary if one exists. **Makes no model call and no
         *     ``materialize``/fetch.**
         *
         *     A cold-tier search on an obscure ticker must not silently trigger a model call
         *     (design §7), and the same principle applies to the SEC/enrichment fetches
         *     ``materialize`` would run. The GET first consults the cache directly; only on a
         *     miss does it build the ``AnalysisResponse`` to compute a stable ``data_as_of`` for
         *     the ``unavailable`` reason, and even then it makes no model call — the client
         *     renders a Generate action rather than a spinner.
         */
        get: operations["get_summary_research__symbol__summary_get"];
        put?: never;
        /**
         * Post Summary
         * @description Generate and cache a summary on demand. Fail-soft: a failed generation returns
         *     ``pending`` with a reason, not an error, so the rest of the page is untouched.
         */
        post: operations["post_summary_research__symbol__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe */
        get: operations["universe_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlist
         * @description Return this user's watchlist items. A second user's items are not returned.
         */
        get: operations["list_watchlist_watchlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Symbol
         * @description Add *symbol* to this user's watchlist. Idempotent: a repeat is 200, not an error.
         *
         *     Returns 201 on first add, 200 on a repeat. 404 if the symbol is not a known filer — we
         *     never create a row that can never resolve to a name. Adding a symbol promotes it to the
         *     warm tier immediately (``warm_symbols`` reads ``WatchlistItemRow``).
         */
        post: operations["add_symbol_watchlist__symbol__post"];
        /**
         * Remove Symbol
         * @description Remove *symbol* from this user's watchlist. Idempotent: a repeat delete is 204.
         */
        delete: operations["remove_symbol_watchlist__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlternativeStrike
         * @description Another contract assessed on the same underlying during the same run.
         */
        AlternativeStrike: {
            /** Blended Score */
            blended_score?: number | null;
            /** Candidate Id */
            candidate_id: string;
            /** Expiry */
            expiry?: string | null;
            /** Premium */
            premium?: number | null;
            /** Reasons */
            reasons?: string[];
            /** Right */
            right?: string | null;
            /** Stage */
            stage?: string | null;
            /** Strategy */
            strategy: string;
            /** Strike */
            strike: number;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * @default {
             *       "state": "pending"
             *     }
             */
            checks: components["schemas"]["Section_ChecksPayload_"];
            /** Exchange */
            exchange?: string | null;
            fundamentals: components["schemas"]["Section_NormalizedFinancials_"];
            /**
             * Is Etf
             * @default false
             */
            is_etf: boolean;
            /** Name */
            name: string;
            /**
             * @default {
             *       "state": "pending"
             *     }
             */
            news: components["schemas"]["Section_list_NewsItem__"];
            quote?: components["schemas"]["Sourced_float_"] | null;
            /**
             * @default {
             *       "state": "pending"
             *     }
             */
            sentiment: components["schemas"]["Section_SentimentDetail_"];
            /** Symbol */
            symbol: string;
            /**
             * @default {
             *       "state": "pending"
             *     }
             */
            technicals: components["schemas"]["Section_TechnicalStats_"];
        };
        /**
         * ApprovalDetail
         * @description One approval in full, with the joined enrichment.
         */
        ApprovalDetail: {
            /** Alternatives */
            alternatives?: components["schemas"]["AlternativeStrike"][];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Blended Score */
            blended_score?: number | null;
            /** Candidate Id */
            candidate_id: string;
            /** Contracts */
            contracts: number;
            /** Decided At */
            decided_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Expiry */
            expiry?: string | null;
            /** Gate Reasons */
            gate_reasons?: string[];
            /** Id */
            id: number;
            ideal?: components["schemas"]["IdealZonePayload"] | null;
            /** Order State */
            order_state?: string | null;
            /** Premium */
            premium?: number | null;
            review?: components["schemas"]["ClaudeReviewPayload"] | null;
            /** Right */
            right: string;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @enum {string}
             */
            source: "scan" | "roll";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected" | "expired";
            /** Strategy */
            strategy: string;
            /** Strike */
            strike: number;
            /** Underlying */
            underlying: string;
        };
        /** ApprovalListResponse */
        ApprovalListResponse: {
            /** Approvals */
            approvals?: components["schemas"]["ApprovalSummary"][];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
        };
        /**
         * ApprovalSummary
         * @description One row in the approvals list.
         */
        ApprovalSummary: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Blended Score */
            blended_score?: number | null;
            /** Candidate Id */
            candidate_id: string;
            /** Contracts */
            contracts: number;
            /** Decided At */
            decided_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Expiry */
            expiry?: string | null;
            /** Id */
            id: number;
            /** Order State */
            order_state?: string | null;
            /** Premium */
            premium?: number | null;
            /** Right */
            right: string;
            /**
             * Source
             * @enum {string}
             */
            source: "scan" | "roll";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected" | "expired";
            /** Strategy */
            strategy: string;
            /** Strike */
            strike: number;
            /** Underlying */
            underlying: string;
        };
        /** AssessedContract */
        AssessedContract: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Blended Score */
            blended_score?: number | null;
            /** Candidate Id */
            candidate_id: string;
            /** Expiry */
            expiry?: string | null;
            ideal?: components["schemas"]["IdealZonePayload"] | null;
            /** Premium */
            premium?: number | null;
            /** Promotable */
            promotable: boolean;
            /** Promote Note */
            promote_note?: string | null;
            /** Reasons */
            reasons?: string[];
            /** Reasons Text */
            reasons_text?: string[];
            /**
             * Stage
             * @enum {string}
             */
            stage: "generator" | "risk_gate" | "score_floor" | "dedupe" | "top_n" | "passed";
            /** Strategy */
            strategy: string;
            /** Strike */
            strike?: number | null;
            /** Symbol */
            symbol: string;
        };
        /** AssessedGroup */
        AssessedGroup: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Contracts */
            contracts?: components["schemas"]["AssessedContract"][];
            /** Counts */
            counts?: {
                [key: string]: number;
            };
            /** Symbol */
            symbol: string;
        };
        /** AssessedResponse */
        AssessedResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Computed At */
            computed_at?: string | null;
            /** Groups */
            groups?: components["schemas"]["AssessedGroup"][];
            /** Run Id */
            run_id?: string | null;
        };
        /** AutonomyRung */
        AutonomyRung: {
            /** Label */
            label: string;
            /** Level */
            level: string;
        };
        /**
         * Bar
         * @description One daily OHLCV bar in lightweight-charts' expected field names.
         *
         *     ``time`` is a ``YYYY-MM-DD`` string (lightweight-charts accepts the date prefix of an
         *     ISO timestamp for a daily series). No client-side remapping is needed.
         */
        Bar: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Time */
            time: string;
            /** Volume */
            volume: number;
        };
        /**
         * BarsResponse
         * @description Daily bars with server-side SMA 50 and 200 overlays.
         *
         *     ``sma50``/``sma200`` are parallel lists aligned to ``bars``: ``None`` until enough
         *     data exists to compute the moving average at that index, then the value. Computed
         *     server-side from ``daily_bars`` so the chart and the technical panel can never disagree.
         */
        BarsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Bars
             * @default []
             */
            bars: components["schemas"]["Bar"][];
            /**
             * Sma200
             * @default []
             */
            sma200: (number | null)[];
            /**
             * Sma50
             * @default []
             */
            sma50: (number | null)[];
        };
        /**
         * BuyCandidateOut
         * @description One buy-to-own recommendation, rendered exactly as the scan scored it.
         *
         *     The web layer does no re-scoring: every field below is the value
         *     ``generate_buy_candidates`` produced at scan time, persisted via
         *     ``BuyCandidateRow`` and read back unmodified so the site and Telegram can never
         *     disagree about what the system thinks.
         */
        BuyCandidateOut: {
            /** Current Iv */
            current_iv?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Est Monthly Cc Yield */
            est_monthly_cc_yield?: number | null;
            /** Fundamental Score */
            fundamental_score?: number | null;
            /** Hv 30 */
            hv_30?: number | null;
            /** Iv Rank */
            iv_rank?: number | null;
            /** Iv Score */
            iv_score?: number | null;
            /** Next Earnings */
            next_earnings?: string | null;
            /** Price */
            price?: number | null;
            /** Quality Flag */
            quality_flag?: boolean | null;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Score */
            score: number;
            /** Sector */
            sector?: string | null;
            /** Sma 200 */
            sma_200?: number | null;
            /** Sma 50 */
            sma_50?: number | null;
            /** Symbol */
            symbol: string;
            /** Technical Regime */
            technical_regime?: string | null;
            /** Technical Score */
            technical_score?: number | null;
            /** Vrp */
            vrp?: number | null;
        };
        /** CategoryPayload */
        CategoryPayload: {
            /** Category */
            category: string;
            /**
             * Checks
             * @default []
             */
            checks: components["schemas"]["CheckResult"][];
            /** Evaluable */
            evaluable: number;
            /** Failed */
            failed: number;
            /**
             * Not Applicable
             * @default false
             */
            not_applicable: boolean;
            /** Note */
            note?: string | null;
            /** Passed */
            passed: number;
            /** Total */
            total: number;
            /** Unknown */
            unknown: number;
        };
        /** CheckResult */
        CheckResult: {
            /** Actual */
            actual?: number | null;
            /** Category */
            category: string;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            state: components["schemas"]["CheckState"];
            /** Statement */
            statement: string;
            /** Threshold */
            threshold?: number | number[] | null;
        };
        /**
         * CheckState
         * @enum {string}
         */
        CheckState: "PASS" | "FAIL" | "UNKNOWN" | "NOT_APPLICABLE";
        /** ChecksPayload */
        ChecksPayload: {
            /** Categories */
            categories: components["schemas"]["CategoryPayload"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["Warning"][];
        };
        /**
         * ClaudeReviewPayload
         * @description Claude's five review fields, surfaced separately — never one prose blob.
         *
         *     Telegram renders these as one chat bubble; the console renders them as five
         *     labelled sections beside the numbers they refer to. ``rolling_considerations``
         *     is the fifth and may be empty on the full-universe path.
         */
        ClaudeReviewPayload: {
            /**
             * Assignment Considerations
             * @default
             */
            assignment_considerations: string;
            /** Confidence */
            confidence?: number | null;
            /** Priority */
            priority?: number | null;
            /** Recommendation */
            recommendation?: string | null;
            /**
             * Risks
             * @default
             */
            risks: string;
            /**
             * Rolling Considerations
             * @default
             */
            rolling_considerations: string;
            /**
             * Tradeoffs
             * @default
             */
            tradeoffs: string;
            /**
             * Why Attractive
             * @default
             */
            why_attractive: string;
        };
        /**
         * CommandKind
         * @description Every intent the web layer can enqueue. Later milestones register handlers.
         * @enum {string}
         */
        CommandKind: "approve" | "reject" | "promote" | "roll_request" | "halt" | "resume" | "set_autonomy" | "universe_add" | "universe_remove" | "refresh";
        /** CommandRequest */
        CommandRequest: {
            kind: components["schemas"]["CommandKind"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** CommandResponse */
        CommandResponse: {
            /** Applied At */
            applied_at?: string | null;
            /**
             * As Of
             * Format: date-time
             */
            as_of?: string;
            /**
             * Created
             * @default false
             */
            created: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            kind: components["schemas"]["CommandKind"];
            /**
             * Needs Confirmation
             * @default false
             */
            needs_confirmation: boolean;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "applied" | "failed" | "expired";
        };
        /**
         * CommandStatus
         * @description The status of a command, returned by ``GET /commands/{id}`` and ``POST /commands``.
         */
        CommandStatus: {
            /** Applied At */
            applied_at?: string | null;
            /**
             * As Of
             * Format: date-time
             */
            as_of?: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            kind: components["schemas"]["CommandKind"];
            /**
             * Needs Confirmation
             * @default false
             */
            needs_confirmation: boolean;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "applied" | "failed" | "expired";
        };
        /** ConfirmRequest */
        ConfirmRequest: {
            /**
             * Confirm Token
             * @default
             */
            confirm_token: string;
        };
        /** ControlsResponse */
        ControlsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            autonomy: components["schemas"]["AutonomyRung"];
            /** Drain Healthy */
            drain_healthy: boolean;
            /** Drain Last Seen */
            drain_last_seen?: string | null;
            /** Halt Reason */
            halt_reason?: string | null;
            /** Halted */
            halted: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "paper" | "live";
            /** Pending Commands */
            pending_commands: number;
            /** Rungs */
            rungs?: components["schemas"]["AutonomyRung"][];
        };
        /** FillListResponse */
        FillListResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Fills */
            fills?: components["schemas"]["FillSummary"][];
        };
        /** FillSummary */
        FillSummary: {
            /** Action */
            action: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Avg Price */
            avg_price: number;
            /** Candidate Id */
            candidate_id: string;
            /** Commission */
            commission?: number | null;
            /**
             * Filled At
             * Format: date-time
             */
            filled_at: string;
            /** Filled Qty */
            filled_qty: number;
            /** Id */
            id: number;
            /** Is Live */
            is_live: boolean;
            /** Order Id */
            order_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Providers
             * @default {}
             */
            providers: {
                [key: string]: string;
            };
            /** Research Db */
            research_db: boolean;
            /** Status */
            status: string;
            /** Trading Db */
            trading_db: boolean;
            /** Worker Heartbeat */
            worker_heartbeat?: string | null;
        };
        /**
         * IdealZonePayload
         * @description The denormalised ideal zone from ``RiskVerdictRow`` (lo / hi / min_credit).
         */
        IdealZonePayload: {
            /** Hi */
            hi?: number | null;
            /** Lo */
            lo?: number | null;
            /** Min Credit */
            min_credit?: number | null;
        };
        /**
         * LineItemValue
         * @description One normalised line item for one period, traceable to its filing.
         */
        LineItemValue: {
            /** Accn */
            accn?: string | null;
            /** Concept */
            concept?: string | null;
            /** Filed */
            filed?: string | null;
            /** Form */
            form?: string | null;
            /** Line Item */
            line_item: string;
            /** Value */
            value: number | null;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Id */
            id: string;
            /** Role */
            role: string;
        };
        /** NavResponse */
        NavResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Sections */
            sections: components["schemas"]["NavSection"][];
        };
        /** NavSection */
        NavSection: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Available */
            available: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
        };
        /**
         * NewsItem
         * @description One news headline with its per-item VADER sentiment.
         *
         *     ``sentiment`` is the VADER compound polarity in -1.0..+1.0 (0.0 = neutral/unavailable).
         *     The frontend renders it as a labelled chip (label + tint, never colour-only).
         */
        NewsItem: {
            /** Published At */
            published_at?: string | null;
            /** Sentiment */
            sentiment?: number | null;
            /** Source */
            source?: string | null;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /** NormalizedFinancials */
        NormalizedFinancials: {
            /**
             * Annual
             * @default []
             */
            annual: components["schemas"]["PeriodStatement"][];
            /** Cik */
            cik: string;
            /**
             * Entity Name
             * @default
             */
            entity_name: string;
            /**
             * Quarterly
             * @default []
             */
            quarterly: components["schemas"]["PeriodStatement"][];
            /** Symbol */
            symbol: string;
        };
        /**
         * OptionsCoverage
         * @description What the on-demand options lens could actually check.
         *
         *     ``option_chain`` is always ``false`` in P1 — the API process holds no IBKR
         *     connection, so ``atm_open_interest``/``atm_spread_pct`` stay ``UNKNOWN`` and the
         *     response says so rather than the UI quietly showing blanks.
         */
        OptionsCoverage: {
            /** Iv History */
            iv_history: boolean;
            /**
             * Option Chain
             * @default false
             */
            option_chain: boolean;
        };
        /**
         * OptionsLensResponse
         * @description ``GET /research/{symbol}/options`` — the on-demand options-income checks lens.
         *
         *     ``in_universe``/``tier`` reflect whether *symbol* is one of the ~46 `universe.yaml`
         *     names (the "hot" tier, with full IV history) or anything else ("cold", best-effort).
         *     ``checks`` is the catalogue's `options` category only. `iv_rank`/`vrp_points` are read
         *     real from the trading DB for a universe name; for an off-universe name with no
         *     `iv_history` they resolve to `UNKNOWN` rather than a percentile invented from a short
         *     series — `coverage.iv_history` names which case applied.
         */
        OptionsLensResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Checks
             * @default []
             */
            checks: components["schemas"]["CheckResult"][];
            coverage: components["schemas"]["OptionsCoverage"];
            /** In Universe */
            in_universe: boolean;
            /** Symbol */
            symbol: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "hot" | "cold";
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["Warning"][];
        };
        /** OrderListResponse */
        OrderListResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Orders */
            orders?: components["schemas"]["OrderSummary"][];
        };
        /** OrderSummary */
        OrderSummary: {
            /** Approval Id */
            approval_id?: number | null;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Avg Fill Price */
            avg_fill_price?: number | null;
            /** Candidate Id */
            candidate_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail */
            detail?: string | null;
            /** Expiry */
            expiry?: string | null;
            /** Filled Qty */
            filled_qty: number;
            /** Id */
            id: number;
            /** Is Live */
            is_live: boolean;
            /** Limit Price */
            limit_price?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "submitted" | "filled" | "partial" | "cancelled" | "rejected";
            /** Strategy */
            strategy: string;
            /** Strike */
            strike: number;
            /** Underlying */
            underlying: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PeriodStatement
         * @description Every line item for one reporting period.
         */
        PeriodStatement: {
            /** Items */
            items: {
                [key: string]: components["schemas"]["LineItemValue"];
            };
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Period Type */
            period_type: string;
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "base" | "uptrend" | "distribution" | "downtrend";
        /**
         * RecommendationsResponse
         * @description ``GET /research/recommendations`` — the buy list the scan produced.
         *
         *     ``computed_at`` is the most recent full scan's compute time (the run the displayed
         *     candidates came from). ``as_of`` is the request time. ``candidates`` is empty (not
         *     an error) when no full scan has run yet; the route still returns 200 in that case.
         */
        RecommendationsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["BuyCandidateOut"][];
            /** Computed At */
            computed_at?: string | null;
        };
        /**
         * Regime
         * @enum {string}
         */
        Regime: "bullish" | "bearish" | "sideways" | "high_volatility" | "low_volatility";
        /** RollAlertSummary */
        RollAlertSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail */
            detail: string;
            /** Id */
            id: number;
            /** Trigger */
            trigger: string;
        };
        /** SearchHit */
        SearchHit: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Is Etf
             * @default false
             */
            is_etf: boolean;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchHit"][];
        };
        /**
         * SectionState
         * @enum {string}
         */
        SectionState: "ready" | "pending" | "unavailable";
        /** Section[ChecksPayload] */
        Section_ChecksPayload_: {
            data?: components["schemas"]["ChecksPayload"] | null;
            /** Reason */
            reason?: string | null;
            state: components["schemas"]["SectionState"];
        };
        /** Section[NormalizedFinancials] */
        Section_NormalizedFinancials_: {
            data?: components["schemas"]["NormalizedFinancials"] | null;
            /** Reason */
            reason?: string | null;
            state: components["schemas"]["SectionState"];
        };
        /** Section[SentimentDetail] */
        Section_SentimentDetail_: {
            data?: components["schemas"]["SentimentDetail"] | null;
            /** Reason */
            reason?: string | null;
            state: components["schemas"]["SectionState"];
        };
        /** Section[TechnicalStats] */
        Section_TechnicalStats_: {
            data?: components["schemas"]["TechnicalStats"] | null;
            /** Reason */
            reason?: string | null;
            state: components["schemas"]["SectionState"];
        };
        /** Section[list[NewsItem]] */
        Section_list_NewsItem__: {
            /** Data */
            data?: components["schemas"]["NewsItem"][] | null;
            /** Reason */
            reason?: string | null;
            state: components["schemas"]["SectionState"];
        };
        /**
         * SectorCard
         * @description One sector's aggregate summary for the landing-page grid.
         *
         *     ``avg_iv_rank`` is the differentiator: where premium is rich today, at a glance —
         *     no consumer research site shows it. ``iv_rank_count`` is the number of members that
         *     actually contributed to that average, so a one-name average is visible as such
         *     (and ``avg_iv_rank`` is ``None`` when no member has IV history).
         *     ``change_pct`` is ``None`` (never ``0``) when no member has a priced quote.
         *     Cards are ordered by ``avg_iv_rank`` descending on the client, since premium
         *     richness is the reason to look.
         */
        SectorCard: {
            /** Avg Iv Rank */
            avg_iv_rank?: number | null;
            best: components["schemas"]["SectorMover"];
            /** Change Pct */
            change_pct?: number | null;
            /** Count */
            count: number;
            /**
             * Iv Rank Count
             * @default 0
             */
            iv_rank_count: number;
            /** Sector */
            sector: string;
            worst: components["schemas"]["SectorMover"];
        };
        /**
         * SectorMover
         * @description One symbol and its daily change, for the best/worst corner of a sector card.
         */
        SectorMover: {
            /** Change Pct */
            change_pct?: number | null;
            /** Symbol */
            symbol: string;
        };
        /**
         * SectorsResponse
         * @description ``GET /research/sectors`` — the sector card grid.
         */
        SectorsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Sectors
             * @default []
             */
            sectors: components["schemas"]["SectorCard"][];
        };
        /**
         * SentimentDetail
         * @description Composite social + news sentiment for one symbol — enrichment only.
         *
         *     ``overall`` (0-100, 50 = neutral, ``None`` = no data from any source) is the single
         *     number that feeds scoring via :attr:`ScoreCard.sentiment_score`. The per-source fields,
         *     counts, 1-day velocity, and headline are surfaced to Claude and the Telegram deep-dive
         *     card to *explain* the read; they never reach the risk engine or position sizing.
         */
        SentimentDetail: {
            /** Delta 1D */
            delta_1d?: number | null;
            /**
             * Label
             * @default no data
             */
            label: string;
            /** News */
            news?: number | null;
            /**
             * News Count
             * @default 0
             */
            news_count: number;
            /** Overall */
            overall?: number | null;
            /** Reddit */
            reddit?: number | null;
            /** Stocktwits */
            stocktwits?: number | null;
            /**
             * Stocktwits Msgs
             * @default 0
             */
            stocktwits_msgs: number;
            /** Top Headline */
            top_headline?: string | null;
        };
        /** ShortListResponse */
        ShortListResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Shorts */
            shorts?: components["schemas"]["ShortPosition"][];
        };
        /** ShortPosition */
        ShortPosition: {
            /** Alerts */
            alerts?: components["schemas"]["RollAlertSummary"][];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Assignment Risk */
            assignment_risk: boolean;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Contracts */
            contracts: number;
            delta?: components["schemas"]["Sourced_float_"] | null;
            /** Dte */
            dte?: number | null;
            /** Expiry */
            expiry?: string | null;
            /** Mark */
            mark?: number | null;
            /** Pnl Pct */
            pnl_pct?: number | null;
            /** Position Symbol */
            position_symbol: string;
            /**
             * Right
             * @enum {string}
             */
            right: "C" | "P";
            /** Strike */
            strike: number;
            /** Underlying */
            underlying: string;
            /** Unrealized Pnl */
            unrealized_pnl?: number | null;
        };
        /**
         * Source
         * @description Where a number came from. A Black-Scholes delta must not look like an IBKR one.
         * @enum {string}
         */
        Source: "edgar" | "yfinance" | "stooq" | "ibkr" | "computed";
        /** Sourced[float] */
        Sourced_float_: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            source: components["schemas"]["Source"];
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Value */
            value?: number | null;
        };
        /**
         * SummaryOut
         * @description The AI narrative over computed values. Enrichment — influences nothing.
         *
         *     Every number the model used was passed in via ``ResearchContext``; the model never
         *     calculates. ``caveats`` always carries the quantitative limit. ``model`` and
         *     ``data_as_of`` make a stale summary visibly stale.
         */
        SummaryOut: {
            /**
             * Bear Points
             * @default []
             */
            bear_points: string[];
            /**
             * Bull Points
             * @default []
             */
            bull_points: string[];
            /**
             * Caveats
             * @default []
             */
            caveats: string[];
            /**
             * Data As Of
             * Format: date-time
             */
            data_as_of: string;
            /** Model */
            model: string;
            /** Thesis */
            thesis: string;
            /**
             * Watch Items
             * @default []
             */
            watch_items: string[];
        };
        /**
         * SummaryResponse
         * @description ``GET/POST /research/{symbol}/summary``.
         *
         *     ``state`` is ``ready`` (summary present), ``stale`` (cached but past TTL),
         *     ``unavailable`` (no summary; a GET made no model call), or ``pending`` (a POST
         *     generation was attempted but failed soft). ``reason`` explains ``unavailable``/
         *     ``pending`` so the panel can show why and prompt a Generate/retry action.
         */
        SummaryResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Reason */
            reason?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "stale" | "unavailable" | "pending";
            summary?: components["schemas"]["SummaryOut"] | null;
            /** Symbol */
            symbol: string;
        };
        /** TechnicalStats */
        TechnicalStats: {
            /** Atr 14 */
            atr_14?: number | null;
            /** Atr Ratio */
            atr_ratio?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            phase?: components["schemas"]["Phase"] | null;
            /** Price */
            price: number;
            /**
             * Price Source
             * @default yfinance
             */
            price_source: string;
            regime?: components["schemas"]["Regime"] | null;
            /** Relative Strength */
            relative_strength?: number | null;
            /** Resistance Levels */
            resistance_levels?: number[];
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Sma 20 */
            sma_20?: number | null;
            /** Sma 200 */
            sma_200?: number | null;
            /** Sma 50 */
            sma_50?: number | null;
            /** Support Levels */
            support_levels?: number[];
            /** Symbol */
            symbol: string;
        };
        /**
         * UniverseResponse
         * @description The parsed universe.yaml: the four lists, the sector map, strike-band overrides.
         *
         *     ``sectors`` maps every universe symbol to its sector tag. ``strike_bands`` maps the
         *     symbols that carry a per-symbol override to the band fraction. Both are read-only
         *     in P1; ``editable`` is ``false`` so the client knows not to show an edit control.
         */
        UniverseResponse: {
            /** Actively Wheeling */
            actively_wheeling: string[];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Editable
             * @default false
             */
            editable: boolean;
            /** Indexes */
            indexes: string[];
            /** Sectors */
            sectors: {
                [key: string]: string;
            };
            /** Strike Bands */
            strike_bands: {
                [key: string]: number;
            };
            /** Watchlist */
            watchlist: string[];
            /** Would Own */
            would_own: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Warning
         * @description One surfaced caveat. ``level`` drives the icon/tint; never colour-only.
         */
        Warning: {
            /** Detail */
            detail: string;
            /** Level */
            level: string;
            /** Title */
            title: string;
        };
        /**
         * WatchlistItem
         * @description One row of the user's watchlist, with the fields the landing table needs.
         *
         *     ``price`` ships as ``Sourced<float>`` so its provenance and staleness are explicit.
         *     ``checks`` is the aggregate {passed, evaluable, unknown} — the full per-check payload
         *     lives on the ticker page (M5), one click away. ``iv_rank`` is read-only from the
         *     trading DB's iv_history; ``None`` when the symbol has no IV history.
         */
        WatchlistItem: {
            /** Change Pct */
            change_pct?: number | null;
            /** Checks */
            checks: {
                [key: string]: number;
            };
            /** Iv Rank */
            iv_rank?: number | null;
            /** Name */
            name: string;
            /** Next Earnings */
            next_earnings?: string | null;
            price?: components["schemas"]["Sourced_float_"] | null;
            /** Symbol */
            symbol: string;
        };
        /**
         * WatchlistResponse
         * @description ``GET /watchlist`` — the user's tracked symbols, scoped to their user_id.
         */
        WatchlistResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["WatchlistItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_commands_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_command_commands__command_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                command_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_command_commands__command_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                command_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    nav_nav_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavResponse"];
                };
            };
        };
    };
    list_approvals_options_approvals_get: {
        parameters: {
            query?: {
                /** @description Filter by approval status, or `all` for every status (newest first). */
                status?: "pending" | "approved" | "rejected" | "expired" | "all";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_options_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessed_options_assessed_get: {
        parameters: {
            query?: {
                run?: string;
                symbol?: string | null;
                /** @description Filter to one assessment stage. Unknown values return 422. */
                stage?: ("generator" | "risk_gate" | "score_floor" | "dedupe" | "top_n" | "passed") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    controls_options_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlsResponse"];
                };
            };
        };
    };
    list_fills_options_fills_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_options_orders_get: {
        parameters: {
            query?: {
                /** @description `working` (queued/submitted/partial), `all`, or a specific state. */
                state?: "working" | "all" | "queued" | "submitted" | "filled" | "partial" | "cancelled" | "rejected";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shorts_options_shorts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortListResponse"];
                };
            };
        };
    };
    recommendations_research_recommendations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_research_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sectors_research_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorsResponse"];
                };
            };
        };
    };
    analysis_research__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bars_research__symbol__bars_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_lens_research__symbol__options_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsLensResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_research__symbol__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_summary_research__symbol__summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    universe_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseResponse"];
                };
            };
        };
    };
    list_watchlist_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
        };
    };
    add_symbol_watchlist__symbol__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_symbol_watchlist__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
