/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nav */
        get: operations["nav_nav_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Rank: exact ticker, then ticker prefix, then name substring.
         *
         *     Each band is alphabetical within itself. A blank query returns no results rather
         *     than the whole table.
         */
        get: operations["search_research_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bars
         * @description Daily OHLCV with server-side SMA 50 and 200, in lightweight-charts' field names.
         *
         *     ``time`` is ``YYYY-MM-DD`` (lightweight-charts' accepted daily format). SMA 50 and 200
         *     are computed from ``daily_bars`` here so the chart and the technical panel can never
         *     disagree. A symbol with no bars returns empty lists, not an error.
         */
        get: operations["bars_research__symbol__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis
         * @description Full analysis for one symbol.
         *
         *     404 only when the symbol is not a known filer. Everything else degrades per section.
         */
        get: operations["analysis_research__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Is Etf
             * @default false
             */
            is_etf: boolean;
            fundamentals: components["schemas"]["Section_NormalizedFinancials_"];
            /**
             * @default {
             *       "state": "pending"
             *     }
             */
            technicals: components["schemas"]["Section_TechnicalStats_"];
            /**
             * @default {
             *       "state": "pending"
             *     }
             */
            sentiment: components["schemas"]["Section_SentimentDetail_"];
            /**
             * @default {
             *       "state": "pending"
             *     }
             */
            news: components["schemas"]["Section_list_NewsItem__"];
            quote?: components["schemas"]["Sourced_float_"] | null;
        };
        /**
         * Bar
         * @description One daily OHLCV bar in lightweight-charts' expected field names.
         *
         *     ``time`` is a ``YYYY-MM-DD`` string (lightweight-charts accepts the date prefix of an
         *     ISO timestamp for a daily series). No client-side remapping is needed.
         */
        Bar: {
            /** Time */
            time: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /**
         * BarsResponse
         * @description Daily bars with server-side SMA 50 and 200 overlays.
         *
         *     ``sma50``/``sma200`` are parallel lists aligned to ``bars``: ``None`` until enough
         *     data exists to compute the moving average at that index, then the value. Computed
         *     server-side from ``daily_bars`` so the chart and the technical panel can never disagree.
         */
        BarsResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Bars
             * @default []
             */
            bars: components["schemas"]["Bar"][];
            /**
             * Sma50
             * @default []
             */
            sma50: (number | null)[];
            /**
             * Sma200
             * @default []
             */
            sma200: (number | null)[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Status */
            status: string;
            /** Research Db */
            research_db: boolean;
            /** Trading Db */
            trading_db: boolean;
            /** Worker Heartbeat */
            worker_heartbeat?: string | null;
            /**
             * Providers
             * @default {}
             */
            providers: {
                [key: string]: string;
            };
        };
        /**
         * LineItemValue
         * @description One normalised line item for one period, traceable to its filing.
         */
        LineItemValue: {
            /** Line Item */
            line_item: string;
            /** Value */
            value: number | null;
            /** Concept */
            concept?: string | null;
            /** Accn */
            accn?: string | null;
            /** Filed */
            filed?: string | null;
            /** Form */
            form?: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Id */
            id: string;
            /** Role */
            role: string;
        };
        /** NavResponse */
        NavResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Sections */
            sections: components["schemas"]["NavSection"][];
        };
        /** NavSection */
        NavSection: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Available */
            available: boolean;
            /** Note */
            note?: string | null;
        };
        /**
         * NewsItem
         * @description One news headline with its per-item VADER sentiment.
         *
         *     ``sentiment`` is the VADER compound polarity in -1.0..+1.0 (0.0 = neutral/unavailable).
         *     The frontend renders it as a labelled chip (label + tint, never colour-only).
         */
        NewsItem: {
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Source */
            source?: string | null;
            /** Sentiment */
            sentiment?: number | null;
        };
        /** NormalizedFinancials */
        NormalizedFinancials: {
            /** Symbol */
            symbol: string;
            /** Cik */
            cik: string;
            /**
             * Entity Name
             * @default
             */
            entity_name: string;
            /**
             * Annual
             * @default []
             */
            annual: components["schemas"]["PeriodStatement"][];
            /**
             * Quarterly
             * @default []
             */
            quarterly: components["schemas"]["PeriodStatement"][];
        };
        /**
         * PeriodStatement
         * @description Every line item for one reporting period.
         */
        PeriodStatement: {
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Period Type */
            period_type: string;
            /** Items */
            items: {
                [key: string]: components["schemas"]["LineItemValue"];
            };
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "base" | "uptrend" | "distribution" | "downtrend";
        /**
         * Regime
         * @enum {string}
         */
        Regime: "bullish" | "bearish" | "sideways" | "high_volatility" | "low_volatility";
        /** SearchHit */
        SearchHit: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange?: string | null;
            /**
             * Is Etf
             * @default false
             */
            is_etf: boolean;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchHit"][];
        };
        /**
         * SectionState
         * @enum {string}
         */
        SectionState: "ready" | "pending" | "unavailable";
        /** Section[NormalizedFinancials] */
        Section_NormalizedFinancials_: {
            state: components["schemas"]["SectionState"];
            data?: components["schemas"]["NormalizedFinancials"] | null;
            /** Reason */
            reason?: string | null;
        };
        /** Section[SentimentDetail] */
        Section_SentimentDetail_: {
            state: components["schemas"]["SectionState"];
            data?: components["schemas"]["SentimentDetail"] | null;
            /** Reason */
            reason?: string | null;
        };
        /** Section[TechnicalStats] */
        Section_TechnicalStats_: {
            state: components["schemas"]["SectionState"];
            data?: components["schemas"]["TechnicalStats"] | null;
            /** Reason */
            reason?: string | null;
        };
        /** Section[list[NewsItem]] */
        Section_list_NewsItem__: {
            state: components["schemas"]["SectionState"];
            /** Data */
            data?: components["schemas"]["NewsItem"][] | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * SentimentDetail
         * @description Composite social + news sentiment for one symbol — enrichment only.
         *
         *     ``overall`` (0-100, 50 = neutral, ``None`` = no data from any source) is the single
         *     number that feeds scoring via :attr:`ScoreCard.sentiment_score`. The per-source fields,
         *     counts, 1-day velocity, and headline are surfaced to Claude and the Telegram deep-dive
         *     card to *explain* the read; they never reach the risk engine or position sizing.
         */
        SentimentDetail: {
            /** Overall */
            overall?: number | null;
            /**
             * Label
             * @default no data
             */
            label: string;
            /** Delta 1D */
            delta_1d?: number | null;
            /** Stocktwits */
            stocktwits?: number | null;
            /**
             * Stocktwits Msgs
             * @default 0
             */
            stocktwits_msgs: number;
            /** News */
            news?: number | null;
            /**
             * News Count
             * @default 0
             */
            news_count: number;
            /** Reddit */
            reddit?: number | null;
            /** Top Headline */
            top_headline?: string | null;
        };
        /**
         * Source
         * @description Where a number came from. A Black-Scholes delta must not look like an IBKR one.
         * @enum {string}
         */
        Source: "edgar" | "yfinance" | "stooq" | "ibkr" | "computed";
        /** Sourced[float] */
        Sourced_float_: {
            /** Value */
            value?: number | null;
            source: components["schemas"]["Source"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** TechnicalStats */
        TechnicalStats: {
            /** Symbol */
            symbol: string;
            /** Price */
            price: number;
            /** Rsi 14 */
            rsi_14?: number | null;
            /** Atr 14 */
            atr_14?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Sma 20 */
            sma_20?: number | null;
            /** Sma 50 */
            sma_50?: number | null;
            /** Sma 200 */
            sma_200?: number | null;
            /** Support Levels */
            support_levels?: number[];
            /** Resistance Levels */
            resistance_levels?: number[];
            /** Atr Ratio */
            atr_ratio?: number | null;
            regime?: components["schemas"]["Regime"] | null;
            /** Relative Strength */
            relative_strength?: number | null;
            /**
             * Price Source
             * @default yfinance
             */
            price_source: string;
            phase?: components["schemas"]["Phase"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    nav_nav_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavResponse"];
                };
            };
        };
    };
    search_research_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bars_research__symbol__bars_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analysis_research__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
