import type { components } from "@/lib/api-types";

// Aliased from the generated OpenAPI schema, the same convention
// web/components/portfolio/types.ts set in M3 — src/api/models/pnl.py is the
// source of truth these track, regenerated by `npm run gen:api`.
//
// The summary response is namespaced by openapi-typescript
// (`src__api__models__pnl__SummaryResponse`) because the research layer
// already owns a plain `SummaryResponse` name — two routers, one schema file.
export type LedgerResponse = components["schemas"]["LedgerResponse"];
export type LedgerResponseData = LedgerResponse;
export type LedgerFiltersData = components["schemas"]["LedgerFilters"];
export type CampaignPnlData = components["schemas"]["CampaignPnl"];
export type PnlLegData = components["schemas"]["PnlLeg"];
export type PnlSummaryResponse = components["schemas"]["src__api__models__pnl__SummaryResponse"];
export type PnlSummaryData = components["schemas"]["PnlSummary"];
export type PnlBucketData = components["schemas"]["PnlBucket"];
export type EquityResponse = components["schemas"]["EquityResponse"];
export type EquityCurveData = components["schemas"]["EquityCurve"];
export type EquityPointData = components["schemas"]["EquityPoint"];

// P3-P4 M6 Task 6.2 — the score-vs-outcome surface.
export type SystemPerformanceResponse = components["schemas"]["SystemPerformanceResponse"];
export type ScoreOutcomeReportData = components["schemas"]["ScoreOutcomeReport"];
export type ScoreBucketData = components["schemas"]["ScoreBucket"];
export type SignalCorrelationData = components["schemas"]["SignalCorrelation"];
export type VerdictAgreementData = components["schemas"]["VerdictAgreement"];