import type { components } from "@/lib/api-types";

// Aliased from the generated OpenAPI schema (web/lib/api-types.ts, regenerated by
// `npm run gen:api`) rather than hand-duplicated — src/api/models/portfolio.py is
// the source of truth these track. Unlike components/options/types.ts (hand-written
// because those routes predate the generated file), the portfolio routes shipped
// in M2 with api-types.ts already current, so this folder is the first to consume
// it directly.
export type PortfolioSummaryResponse = components["schemas"]["PortfolioSummaryResponse"];
export type AccountBlock = components["schemas"]["AccountBlock"];
export type ExposureBlock = components["schemas"]["ExposureBlock"];
export type SourcedFloat = components["schemas"]["Sourced_float_"];

// Task 3.3 — GET /portfolio/positions. Named `PositionGroupData` (not `PositionGroup`)
// because the `PositionGroup` component in this folder owns that identifier; the
// component's `group` prop is typed against this alias instead.
export type PositionsResponse = components["schemas"]["PositionsResponse"];
export type PositionGroupData = components["schemas"]["PositionGroup"];
export type StockLeg = components["schemas"]["StockLeg"];
export type OptionLeg = components["schemas"]["OptionLeg"];

// Task 3.4 — GET /portfolio/campaigns. Unlike `PositionGroupData` above, no
// `Data` suffix is needed: this folder's components are named `CampaignsPanel`
// and `CampaignThread`, neither of which collides with `CampaignSummary` or
// `CampaignLeg`. `CampaignsResponse` carries only `{ as_of, campaigns }` - no
// `source`/`degraded`/`note` - because campaigns come from a live SQL read
// (`src/storage/campaigns.py::load_campaigns()`), not the portfolio-snapshot
// freshness spine `PositionsResponse`/`PortfolioSummaryResponse` read from.
export type CampaignsResponse = components["schemas"]["CampaignsResponse"];
export type CampaignSummary = components["schemas"]["CampaignSummary"];
export type CampaignLeg = components["schemas"]["CampaignLeg"];

// Task 3.5 — GET /portfolio/calendar. Like PositionsResponse, carries its own
// `source`/`degraded`/`as_of` (the same portfolio-snapshot freshness spine),
// so CalendarPanel renders FreshnessLabel the same way PositionsPanel does.
export type CalendarResponse = components["schemas"]["CalendarResponse"];
export type CalendarDay = components["schemas"]["CalendarDay"];
export type CalendarEntry = components["schemas"]["CalendarEntry"];
