import type { components } from "@/lib/api-types";

// Aliased from the generated OpenAPI schema (web/lib/api-types.ts, regenerated by
// `npm run gen:api`) rather than hand-duplicated — src/api/models/portfolio.py is
// the source of truth these track. Unlike components/options/types.ts (hand-written
// because those routes predate the generated file), the portfolio routes shipped
// in M2 with api-types.ts already current, so this folder is the first to consume
// it directly.
export type PortfolioSummaryResponse = components["schemas"]["PortfolioSummaryResponse"];
export type AccountBlock = components["schemas"]["AccountBlock"];
export type ExposureBlock = components["schemas"]["ExposureBlock"];
export type SourcedFloat = components["schemas"]["Sourced_float_"];

// Task 3.3 — GET /portfolio/positions. Named `PositionGroupData` (not `PositionGroup`)
// because the `PositionGroup` component in this folder owns that identifier; the
// component's `group` prop is typed against this alias instead.
export type PositionsResponse = components["schemas"]["PositionsResponse"];
export type PositionGroupData = components["schemas"]["PositionGroup"];
export type StockLeg = components["schemas"]["StockLeg"];
export type OptionLeg = components["schemas"]["OptionLeg"];
